import type { OfferConfig } from "@/types/offer"
import { OFFER as base } from "@/config/offers/psicopedagogia/offer"

const image = (src: string) => `/images/jardim/${src.split("/").pop()}`
const bonusDetails = [
  ["25 Combinações Lindas de Plantas", "25 Combinações Lindas\nde Plantas", "Referências de plantas que ficam bonitas juntas para deixar seu jardim vertical mais harmônico."],
  ["25 Modelos com Madeira", "25 Modelos de Jardins\ncom Madeira", "Ideias para usar madeira, treliças e painéis e criar uma composição acolhedora."],
  ["25 Jardins Verticais Modernos", "25 Jardins Verticais\nModernos", "Referências atuais para quem quer um canto verde com visual leve e contemporâneo."],
  ["20 Jardins com Plantas Suspensas", "20 Jardins com\nPlantas Suspensas", "Inspirações para dar volume e movimento ao jardim usando plantas suspensas."],
  ["20 Ideias para Organizar os Vasos", "20 Ideias para Organizar\nos Vasos", "Composições prontas para organizar os vasos com equilíbrio e aproveitar melhor a parede."],
  ["25 Jardins Verticais com Flores", "25 Jardins Verticais\ncom Flores", "Referências floridas para trazer mais cor, vida e personalidade ao seu espaço."],
] as const

export const OFFER: OfferConfig = {
  ...base,
  meta: { title: "35 Projetos de Jardins Verticais", description: "35 projetos prontos de jardins verticais para escolher o modelo que combina com seu espaço e montar o seu com mais segurança." },
  palette: { brand: "#4F7A3A", brandDeep: "#284C2A", brandInk: "#18351E", brandDark: "#7DAA57", brandLight: "#B7D59C", brandSubtle: "#EDF5E7", cta: "#16A34A", ctaDeep: "#11863D", ctaDarkest: "#0E6B31", accent: "#D9A441", yellow: "#E7C75F", bg: "#F7F5ED", bgAlt: "#284C2A" },
  hero: { ...base.hero, pill: "PARA DECORAR SEU CANTINHO", titleLine1: "35 Projetos de", titleLine2: "Jardins Verticais", titleLine3: "para transformar sua parede em um canto cheio de vida", image: "/images/jardim/Plano Completo.webp", imageAlt: "Pack 35 Projetos de Jardins Verticais", subtitle: "Escolha um modelo pronto para a sua varanda, muro ou cantinho vazio e tenha uma referência clara para montar um jardim vertical bonito, sem começar do zero.", ctaText: "QUERO ESCOLHER MEU PROJETO", marqueeText: "35 PROJETOS PRONTOS • VÁRIOS ESPAÇOS • ACESSO IMEDIATO • ", marqueeGradient: "linear-gradient(90deg, #284C2A 0%, #4F7A3A 45%, #7DAA57 72%, #284C2A 100%)", bullets: ["35 projetos visuais completos", "Modelos para vários tipos de espaços", "Sugestões de plantas e materiais", "Combinações fáceis de adaptar"] },
  socialProof: { ...base.socialProof, title: "Olha o que nossos clientes que já usam, falam:", testimonials: base.socialProof.testimonials.map((item) => ({ ...item, src: image(item.src), alt: "Visual de apoio do pack de jardins verticais" })) },
  counter: { prefix: "", target: 35, label: "Projetos prontos para você escolher\no jardim que combina com o seu espaço" },
  kitCards: { heading1: "Veja algumas referências que você vai usar para transformar o seu espaço:", images: base.kitCards.images.map((item) => ({ ...item, src: image(item.src), alt: "Referência de projeto de jardim vertical", width: 300, height: 400 })), displayAspect: "portrait" },
  benefits: { title: "PARE DE OLHAR PARA A PAREDE VAZIA SEM SABER O QUE FAZER", ctaText: "QUERO VER OS PROJETOS", items: [{ icon: "🌿", title: "Escolha sem travar", desc: "Veja projetos organizados pelo local e encontre um modelo que faça sentido para a sua casa." }, { icon: "🏡", title: "Aproveite cada cantinho", desc: "Varandas, muros, corredores e áreas pequenas podem ganhar vida sem comprometer a circulação." }, { icon: "🪴", title: "Monte com mais clareza", desc: "Use a disposição dos vasos, a estrutura e as plantas como referência para planejar o seu jardim." }, { icon: "✨", title: "Deixe a casa mais acolhedora", desc: "Transforme um espaço sem graça em um canto verde, bonito e gostoso de olhar todos os dias." }] },
  urgency: { pill: "COMECE PELO SEU ESPAÇO", title: "VOCÊ NÃO PRECISA SER PAISAGISTA PARA TER UM JARDIM VERTICAL BONITO", highlight: "", body: "Em vez de comprar vasos e plantas sem saber como tudo vai ficar, escolha uma referência pronta e adapte ao seu cantinho.", ctaText: "QUERO MEU JARDIM VERTICAL", trust: ["ACESSO IMEDIATO • MATERIAL DIGITAL"] },
  idealPara: { pill: "É PARA VOCÊ", title: "ESTE PACK É IDEAL PARA QUEM QUER:", subtitle: "Um jardim vertical bonito sem precisar imaginar tudo do zero.", items: [{ icon: "🧱", title: "Aproveitar uma parede", desc: "Dar uma nova função a um muro, varanda, corredor ou entrada." }, { icon: "💡", title: "Ter uma ideia pronta", desc: "Escolher um modelo em vez de passar horas tentando imaginar uma composição." }, { icon: "📏", title: "Adaptar ao espaço", desc: "Visualizar opções para áreas pequenas, estreitas e de diferentes formatos." }, { icon: "🌱", title: "Começar com confiança", desc: "Planejar vasos, estrutura e plantas com uma referência clara em mãos." }] },
  deliverables: { ...base.deliverables, pill: "⚡ ACESSO IMEDIATO", title: "TUDO O QUE VOCÊ VAI RECEBER", image: "/images/jardim/Plano Completo.webp", imageAlt: "Pack 35 Projetos de Jardins Verticais", bullets: ["35 projetos visuais completos de jardins verticais", "7 projetos para varandas e sacadas", "7 projetos para muros e quintais", "7 projetos para corredores e espaços estreitos", "7 projetos para áreas de ventilação", "7 projetos para entradas e garagens", "Referências de vasos, estruturas e plantas", "Entrega imediata por e-mail"] },
  bonusSection: { ...base.bonusSection, pill: "EXTRAS INCLUÍDOS", titleLead: "6 BÔNUS", titleHighlight: "EXCLUSIVOS", subtitle: "No Plano Completo, você também recebe referências extras para deixar seu jardim vertical ainda mais bonito.", timerText: "BÔNUS DISPONÍVEIS SOMENTE\nNO PLANO COMPLETO", cardImageAspect: "portrait" },
  bonuses: base.bonuses.map((bonus, index) => ({ ...bonus, front: image(bonus.front), back: image(bonus.back), title: bonusDetails[index][0], titleBreak: bonusDetails[index][1], desc: bonusDetails[index][2], price: "R$ 27,00" })),
  pricing: { titleLead: "ESCOLHA A OPÇÃO", titleHighlight: "IDEAL PARA VOCÊ", plans: [{ ...base.pricing.plans[0], title: "Plano Básico", image: "/images/jardim/Plano Básico.webp", imageAlt: "Plano Básico de Jardins Verticais", oldPrice: "de R$ 39,90", price: "R$ 17,90", installments: "ou 4x de R$ 4,48 no cartão", items: ["35 projetos prontos de jardins verticais", "Projetos para 5 tipos de espaço", "Referências visuais para adaptar", "Acesso imediato ao material digital"], mutedItems: ["Não inclui os bônus do Plano Completo"], ctaText: "QUERO O PLANO BÁSICO", ctaHref: "#" }, { ...base.pricing.plans[1], title: "Plano Completo", image: "/images/jardim/Plano Completo.webp", imageAlt: "Plano Completo de Jardins Verticais", oldPrice: "de R$ 147,00", price: "R$ 27,90", installments: "ou 6x de R$ 5,00 no cartão", items: ["35 projetos prontos de jardins verticais", ...bonusDetails.map(([title]) => `🎁 ${title}`), "Acesso imediato ao material digital"], ctaText: "QUERO O PLANO COMPLETO", ctaHref: "#" }] },
  guarantee: { ...base.guarantee, icon: "/images/jardim/garantia-30-dias.webp", marqueeText: "GARANTIA 30 DIAS • RISCO ZERO • COMPRA SEGURA • ", marqueeGradient: "linear-gradient(90deg, #284C2A 0%, #4F7A3A 50%, #7DAA57 100%)", title: "COMPRA SEGURA COM 30 DIAS DE GARANTIA", body: "Você tem **30 dias de garantia** para conhecer os projetos. Se o material não fizer sentido para você, basta solicitar o reembolso dentro desse período." },
  access: { title: "Como você vai receber seus projetos", ctaText: "QUERO COMEÇAR AGORA", steps: [{ num: "01", title: "Conclua a compra", desc: "Após o pagamento, seu acesso é liberado automaticamente." }, { num: "02", title: "Receba no e-mail", desc: "As instruções chegam no e-mail informado na compra." }, { num: "03", title: "Escolha seu modelo", desc: "Encontre a categoria que combina com o espaço que você quer transformar." }, { num: "04", title: "Adapte e monte", desc: "Use o projeto como referência para criar o seu jardim vertical." }] },
  faq: { title: "Perguntas Frequentes", items: [{ q: "O material é físico ou digital?", a: "É 100% digital. Você recebe o acesso logo após a confirmação do pagamento." }, { q: "Os projetos servem para espaços pequenos?", a: "Sim. O pack inclui projetos para varandas, sacadas, corredores, áreas de ventilação e outros espaços compactos." }, { q: "Preciso entender de paisagismo?", a: "Não. Os projetos foram organizados justamente para ajudar você a escolher uma referência e visualizar como montar." }, { q: "O que vem no Plano Completo?", a: "Você recebe os 35 projetos principais e 6 coleções extras de referências para plantas, madeira, flores, vasos e estilos de jardim." }, { q: "E se eu não gostar do material?", a: "Você conta com 30 dias de garantia para solicitar o reembolso." }] },
  footer: { ...base.footer, showUpdate: false, missionText: "Transforme um espaço vazio em um canto verde, bonito e acolhedor.", copyright: "Copyright © 2026 | Todos os direitos reservados. Este material é protegido pela Lei nº 9.610/98, sendo proibida a reprodução total ou parcial sem autorização." },
}
