import type { OfferConfig } from '@/types/offer'

export const OFFER: OfferConfig = {
  meta: {
    title: "Mapa de Perfil Infantil para Psicopedagogas Iniciantes",
    description: "Um mapa visual e prático para psicopedagogas iniciantes identificarem o perfil da criança e conduzirem o atendimento com mais segurança.",
  },
  palette: {
    brand: "#0EA5E9",
    brandDeep: "#0284C7",
    brandInk: "#0369A1",
    brandDark: "#38BDF8",
    brandLight: "#7DD3FC",
    brandSubtle: "#E0F2FE",
    cta: "#16A34A",
    ctaDeep: "#11863D",
    ctaDarkest: "#0E6B31",
    accent: "#F59E0B",
    yellow: "#FBBF24",
    bg: "#F0F9FF",
    bgAlt: "#F59E0B",
  },
  hero: {
    pill: "MAPA DE PERFIL INFANTIL",
    titleLine1: "Mapa de Perfil Infantil",
    titleLine2: "para psicopedagogas iniciantes",
    titleLine3: "Identifique, escolha e conduza com mais segurança",
    image: "/images/psicopedagogia/Plano Completo.webp",
    imageAlt: "Mapa de Perfil Infantil",
    imageWidth: 340,
    imageHeight: 425,
    subtitle: "Tenha em mãos um mapa visual para identificar perfis infantis e escolher a atividade certa para cada sessão, sem precisar improvisar.",
    ctaText: "QUERO O MAPA DE PERFIL INFANTIL",
    timerLabel: "BÔNUS ENCERRAM EM",
    marqueeText: "15 Perfis Infantis • Atividade-guia para cada perfil • Acesso Imediato • ",
    marqueeGradient: "linear-gradient(90deg, #0EA5E9 0%, #38BDF8 30%, #7DD3FC 55%, #E0F2FE 80%, #0EA5E9 100%)",
    bullets: [
      "Identificar o perfil da criança",
      "Escolher a atividade certa",
      "Definir o objetivo da sessão",
      "Conduzir sem improvisar",
      "Atender com mais segurança",
    ],
  },
  socialProof: {
    title: "Psicopedagogas de todo o Brasil já usam e aprovam",
    testimonials: [
      { src: "/images/psicopedagogia/Depoimento (1).webp", alt: "Depoimento 1", gradient: "linear-gradient(90deg, #0EA5E9, #0284C7)" },
      { src: "/images/psicopedagogia/Depoimento (2).webp", alt: "Depoimento 2", gradient: "linear-gradient(90deg, #16A34A, #11863D)" },
      { src: "/images/psicopedagogia/Depoimento (3).webp", alt: "Depoimento 3", gradient: "linear-gradient(90deg, #7DD3FC, #0EA5E9)" },
      { src: "/images/psicopedagogia/Depoimento (4).webp", alt: "Depoimento 4", gradient: "linear-gradient(90deg, #0284C7, #0369A1)" },
      { src: "/images/psicopedagogia/Depoimento (5).webp", alt: "Depoimento 5", gradient: "linear-gradient(90deg, #16A34A, #F59E0B)" },
      { src: "/images/psicopedagogia/Depoimento (6).webp", alt: "Depoimento 6", gradient: "linear-gradient(90deg, #0EA5E9, #16A34A)" },
      { src: "/images/psicopedagogia/Depoimento (7).webp", alt: "Depoimento 7", gradient: "linear-gradient(90deg, #7DD3FC, #0284C7)" },
    ],
  },
  counter: {
    prefix: "+ de",
    target: 15,
    label: "Perfis Infantis organizados para suas sessões",
  },
  kitCards: {
    heading1: "Veja como é o mapa que você vai usar nas sessões:",
    images: [
      { src: "/images/psicopedagogia/Imagem (1).webp", alt: "Mapa de Perfil Infantil 1", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (2).webp", alt: "Mapa de Perfil Infantil 2", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (3).webp", alt: "Mapa de Perfil Infantil 3", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (4).webp", alt: "Mapa de Perfil Infantil 4", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (5).webp", alt: "Mapa de Perfil Infantil 5", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (6).webp", alt: "Mapa de Perfil Infantil 6", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (7).webp", alt: "Mapa de Perfil Infantil 7", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (8).webp", alt: "Mapa de Perfil Infantil 8", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (9).webp", alt: "Mapa de Perfil Infantil 9", width: 208, height: 134 },
      { src: "/images/psicopedagogia/Imagem (10).webp", alt: "Mapa de Perfil Infantil 10", width: 208, height: 134 },
    ],
  },
  benefits: {
    title: "Por que psicopedagogas iniciantes estão comprando o Mapa de Perfil Infantil?",
    ctaText: "QUERO O MAPA DE PERFIL",
    items: [
      { icon: "🧠", title: "Praticidade", desc: "15 perfis prontos, você identifica a criança e já sabe qual atividade aplicar em cada sessão." },
      { icon: "🎯", title: "Direcionamento", desc: "Cada perfil tem uma atividade-guia específica, sem precisar escolher no improviso." },
      { icon: "📋", title: "Organização", desc: "Um mapa visual que mostra o perfil, o objetivo e a atividade ideal em segundos." },
      { icon: "✅", title: "Segurança", desc: "Mesmo nos primeiros atendimentos, você tem um caminho claro para conduzir a sessão." },
    ],
  },
  urgency: {
    pill: "OPORTUNIDADE ÚNICA",
    title: "Deixe suas sessões mais seguras com um mapa visual pronto para usar",
    highlight: "",
    body: "Enquanto você pensa, outras psicopedagogas já estão usando o mapa nos atendimentos. O preço promocional não dura para sempre.",
    ctaText: "QUERO ACESSAR AGORA",
    trust: ["ACESSO IMEDIATO • ACESSO VITALÍCIO"],
  },
  idealPara: {
    pill: "É PARA VOCÊ",
    title: "ESTE MATERIAL É IDEAL PARA VOCÊ QUE DESEJA:",
    subtitle: "Feito para psicopedagogas iniciantes que querem mais segurança nos primeiros atendimentos.",
    items: [
      { icon: "🚀", title: "Praticidade", desc: "Ter um mapa visual para seguir antes e durante cada atendimento" },
      { icon: "🎯", title: "Direcionamento", desc: "Saber exatamente qual atividade aplicar de acordo com o perfil da criança" },
      { icon: "🧩", title: "Variedade", desc: "Ter opções para cada tipo de perfil infantil sem repetir atividade" },
      { icon: "💪", title: "Preparo", desc: "Entrar na sessão com um caminho claro, mesmo sem experiência prática" },
    ],
  },
  deliverables: {
    pill: "⚡ ACESSO IMEDIATO",
    title: "TUDO O QUE VOCÊ VAI RECEBER",
    titleHighlight: "",
    image: "/images/psicopedagogia/Plano Completo.webp",
    imageAlt: "Mapa de Perfil Infantil",
    bullets: [
      "Mapa de Perfil Infantil para Psicopedagogas Iniciantes",
      "15 perfis infantis organizados",
      "Atividade-guia para cada perfil",
      "Orientação simples de como aplicar",
      "Arquivo digital pronto para imprimir",
      "Material visual e fácil de consultar",
      "Entrega imediata por e-mail",
    ],
  },
  bonusSection: {
    pill: "EXTRA INCLUÍDO",
    titleLead: "6 BÔNUS",
    titleHighlight: "EXCLUSIVOS",
    subtitle: "Além do Mapa de Perfil Infantil, ao adquirir o Plano Completo você também recebe 6 bônus especiais.",
    cardLabel: "BÔNUS",
    touchHint: "Toque na imagem acima para ver o conteúdo.",
    backHint: "Toque para voltar",
    timerText: "BÔNUS DISPONÍVEIS SOMENTE\nNO PLANO COMPLETO",
    freeLabel: "GRÁTIS",
  },
  bonuses: [
    {
      front: "/images/psicopedagogia/bonus-1-frente.webp",
      back: "/images/psicopedagogia/bonus-1-verso.webp",
      title: "Roteiro Sessão Sem Travar",
      titleBreak: "Roteiro Sessão\nSem Travar",
      desc: "Um roteiro prático para saber como conduzir a sessão do início ao fim, sem ficar perdida ou travar no meio do atendimento.",
      price: "R$ 29,90",
    },
    {
      front: "/images/psicopedagogia/bonus-2-frente.webp",
      back: "/images/psicopedagogia/bonus-2-verso.webp",
      title: "Checklist Anti-Improviso",
      titleBreak: "Checklist\nAnti-Improviso",
      desc: "Um checklist simples para preparar a sessão antes da criança chegar, com perfil, objetivo, atividade, materiais e plano B.",
      price: "R$ 12,90",
    },
    {
      front: "/images/psicopedagogia/bonus-3-frente.webp",
      back: "/images/psicopedagogia/bonus-3-verso.webp",
      title: "Atividades Prontas",
      titleBreak: "Atividades Prontas",
      desc: "75 atividades prontas, separadas por perfil infantil, para ter mais opções do que aplicar em cada tipo de criança.",
      price: "R$ 19,90",
    },
    {
      front: "/images/psicopedagogia/bonus-4-frente.webp",
      back: "/images/psicopedagogia/bonus-4-verso.webp",
      title: "Mapa dos Perfis Combinados",
      titleBreak: "Mapa dos Perfis\nCombinados",
      desc: "Um mapa visual para quando a criança apresenta mais de um comportamento, como agitação com impulsividade ou ansiedade com resistência.",
      price: "R$ 19,90",
    },
    {
      front: "/images/psicopedagogia/bonus-5-frente.webp",
      back: "/images/psicopedagogia/bonus-5-verso.webp",
      title: "Fichas de Evolução da Criança",
      titleBreak: "Fichas de Evolução\nda Criança",
      desc: "Fichas práticas para registrar a sessão, acompanhar avanços e planejar o próximo atendimento com mais organização.",
      price: "R$ 12,90",
    },
    {
      front: "/images/psicopedagogia/bonus-6-frente.webp",
      back: "/images/psicopedagogia/bonus-6-verso.webp",
      title: "Kit Visual de Combinados",
      titleBreak: "Kit Visual de\nCombinados",
      desc: "Cards visuais para criar combinados com a criança, organizar a sessão e retomar regras sem transformar tudo em bronca.",
      price: "R$ 12,90",
    },
  ],
  pricing: {
    titleLead: "APROVEITE ENQUANTO",
    titleHighlight: "O PLANO COMPLETO ESTÁ EM PROMOÇÃO!",
    plans: [
      {
        id: "basic",
        title: "Plano Básico",
        image: "/images/psicopedagogia/Plano Básico.webp",
        imageAlt: "Plano Básico",
        featured: false,
        oldPrice: "de R$ 39,90",
        price: "R$ 17,90",
        installments: "ou 4x de R$ 4,47 no cartão",
        items: [
          "Mapa de Perfil Infantil para Psicopedagogas Iniciantes",
          "Arquivo digital em formato visual e prático",
          "Acesso imediato após a confirmação da compra",
          "Material para consultar pelo celular, tablet ou computador",
        ],
        mutedItems: [
          "Não inclui os bônus do Plano Completo",
        ],
        ctaText: "QUERO ESSA OPÇÃO!",
        ctaHref: "https://ggcheckout.app/checkout/v5/0PPwwQUNNadq3EBOBJ8P",
      },
      {
        id: "premium",
        title: "Plano Completo",
        image: "/images/psicopedagogia/Plano Completo.webp",
        imageAlt: "Plano Completo",
        featured: true,
        oldPrice: "de R$ 147,00",
        price: "R$ 27,90",
        installments: "ou 4x de R$ 6,97 no cartão",
        items: [
          "Mapa de Perfil Infantil para Psicopedagogas Iniciantes",
          "🎁 Bônus 01: Roteiro Sessão Sem Travar",
          "🎁 Bônus 02: Checklist Anti-Improviso",
          "🎁 Bônus 03: Atividades Prontas",
          "🎁 Bônus 04: Mapa dos Perfis Combinados",
          "🎁 Bônus 05: Fichas de Evolução da Criança",
          "🎁 Bônus 06: Kit Visual de Combinados",
          "Envio imediato por e-mail",
          "Acesso ao material pelo celular, tablet ou computador",
          "Compra segura",
        ],
        ctaText: "QUERO O PLANO COMPLETO!",
        ctaHref: "https://ggcheckout.app/checkout/v5/ynv8yHYYJNcf0Y4GQe9F",
      },
    ],
  },
  guarantee: {
    marqueeText: "GARANTIA 30 DIAS • RISCO ZERO • SATISFAÇÃO OU DINHEIRO DE VOLTA • ",
    marqueeGradient: "linear-gradient(90deg, #0EA5E9 0%, #38BDF8 30%, #7DD3FC 55%, #E0F2FE 80%, #0EA5E9 100%)",
    icon: "/images/psicopedagogia/garantia-30-dias.webp",
    iconAlt: "Garantia de 30 dias",
    title: "Compra 100% segura e garantida!",
    body: "Você tem **30 dias de garantia** para testar o material. Se não gostar por qualquer motivo, devolvemos 100% do valor. Sem perguntas, sem burocracia.",
  },
  access: {
    title: "Como você vai receber seu Mapa de Perfil Infantil",
    steps: [
      { num: "01", title: "Conclua sua compra", desc: "Após o pagamento, seu acesso é liberado automaticamente." },
      { num: "02", title: "Receba no e-mail", desc: "As instruções chegam diretamente no e-mail cadastrado na compra." },
      { num: "03", title: "Acesse os materiais", desc: "Tudo organizado em PDF, pronto para baixar e usar." },
      { num: "04", title: "Use nas sessões", desc: "Consulte pelo celular, tablet ou computador antes ou durante o atendimento." },
    ],
  },
  faq: {
    title: "Perguntas Frequentes",
    items: [
      { q: "Como vou receber o Mapa de Perfil Infantil?", a: "Você recebe os arquivos por e-mail logo após a confirmação da compra." },
      { q: "O material é físico ou digital?", a: "É 100% digital. Você recebe o PDF para baixar, imprimir e consultar no celular, tablet ou computador." },
      { q: "Preciso editar alguma coisa?", a: "Não. O mapa já vem pronto. Você não precisa de Canva, programas ou design." },
      { q: "O que vem no Plano Completo?", a: "O Mapa de Perfil Infantil + 6 bônus: Roteiro Sessão Sem Travar, Checklist Anti-Improviso, Atividades Prontas, Mapa dos Perfis Combinados, Fichas de Evolução e Kit Visual de Combinados." },
      { q: "E se eu comprar e não gostar?", a: "Você tem 30 dias de garantia. Se não for para você, basta solicitar o reembolso e devolvemos 100% do valor." },
    ],
  },
  footer: {
    updateTitle: "Material em constante atualização",
    updateBody: "O Mapa de Perfil Infantil recebe novos perfis e atividades periodicamente. Ao adquirir agora, você garante acesso vitalício e todas as atualizações futuras.",
    copyright: "Copyright © 2026 | Todos os direitos reservados. Este material é protegido pela Lei nº 9.610/98, sendo proibida a reprodução total ou parcial sem autorização.",
    missionText: "Conduza suas sessões psicopedagógicas com mais segurança, clareza e menos improviso",
    privacyUrl: "/psicopedagogia/politica-de-privacidade",
    termsUrl: "/psicopedagogia/termos-de-uso",
    privacyLabel: "Política de Privacidade",
    termsLabel: "Termos de Uso",
  },
}
