import type { OfferConfig } from "@/types/offer"
import { OFFER as laboralOffer } from "@/config/offers/laboral/offer"

const bonuses = [
  {
    title: "Exame de Consciência de Bolso",
    titleBreak: "Exame de Consciência\nde Bolso",
    desc: "Um exame visual, resumido e organizado. Pode ser consultado pelo celular ou impresso em formato dobrável antes da confissão.",
    price: "R$ 27,00",
  },
  {
    title: "40 Perguntas para Preparar sua Confissão",
    titleBreak: "40 Perguntas para\nPreparar sua Confissão",
    desc: "Uma coleção de perguntas práticas para reconhecer faltas, omissões, hábitos e atitudes presentes na vida cotidiana.",
    price: "R$ 27,00",
  },
  {
    title: "Orações para Antes e Depois da Confissão",
    titleBreak: "Orações Antes e Depois\nda Confissão",
    desc: "Uma seleção de orações curtas para pedir sinceridade, arrependimento, coragem, serenidade e gratidão.",
    price: "R$ 27,00",
  },
  {
    title: "Guia Visual da Primeira Missa Depois da Confissão",
    titleBreak: "Guia da Primeira Missa\nDepois da Confissão",
    desc: "Um material mostrando como se preparar para voltar à Missa e participar com mais atenção e reverência.",
    price: "R$ 27,00",
  },
  {
    title: "Calendário de Vida Sacramental",
    titleBreak: "Calendário de Vida\nSacramental",
    desc: "Um calendário para registrar confissões, Missas importantes, períodos penitenciais e momentos de preparação espiritual.",
    price: "R$ 27,00",
  },
  {
    title: "Exame Diário de Cinco Minutos",
    titleBreak: "Exame Diário de\nCinco Minutos",
    desc: "Um roteiro para revisar o dia com gratidão, reconhecer falhas e escolher uma atitude para o dia seguinte.",
    price: "R$ 27,00",
  },
] as const

const confissaoImage = (filename: string) => `/images/confissao/${filename}`

export const OFFER: OfferConfig = {
  ...laboralOffer,
  meta: {
    title: "Guia Visual da Confissão",
    description: "Um passo a passo visual para organizar o exame de consciência, saber o que dizer ao padre e se confessar com tranquilidade.",
  },
  palette: {
    brand: "#78350F",
    brandDeep: "#451A03",
    brandInk: "#2D160A",
    brandDark: "#A16207",
    brandLight: "#E8C77F",
    brandSubtle: "#FEF3C7",
    cta: "#16A34A",
    ctaDeep: "#15803D",
    ctaDarkest: "#166534",
    accent: "#9F1239",
    yellow: "#D4A72C",
    bg: "#FFF9ED",
    bgAlt: "#451A03",
  },
  hero: {
    ...laboralOffer.hero,
    pill: "PARA QUEM VAI SE CONFESSAR",
    titleLine1: "Guia Visual",
    titleLine2: "da Confissão",
    titleLine3: "",
    image: confissaoImage("Plano Completo.webp"),
    subtitle: "Prepare sua confissão com um passo a passo visual para organizar o exame de consciência, saber o que dizer ao padre e sair do confessionário sem a sensação de ter feito algo errado.",
    imageAlt: "Guia Visual da Confissão",
    ctaText: "QUERO ACESSAR AGORA",
    marqueeText: "GUIA VISUAL ✦ EXAME DE CONSCIÊNCIA ✦ PASSO A PASSO ✦ ACESSO IMEDIATO ✦ ",
    marqueeGradient: "linear-gradient(90deg, var(--brand) 0%, var(--brand-deep) 100%)",
    bullets: [
      "Passo a passo visual para cada etapa da confissão",
      "Exame de consciência organizado por áreas da vida",
      "Frases prontas para saber o que confessar ao padre",
      "Orientações para o que fazer depois da confissão",
    ],
  },
  socialProof: {
    ...laboralOffer.socialProof,
    title: "VEJA O QUE NOSSOS CLIENTES ESTÃO DIZENDO",
    testimonials: laboralOffer.socialProof.testimonials.slice(0, 5).map((testimonial, index) => ({
      ...testimonial,
      src: confissaoImage(`Depoimento (${index + 1}).webp`),
      alt: "Depoimento de cliente do Guia Visual da Confissão",
    })),
  },
  counter: {
    prefix: "+ de",
    target: 25,
    label: "Páginas com o passo a passo visual para sua confissão",
  },
  kitCards: {
    ...laboralOffer.kitCards,
    heading1: "VEJA O GUIA VISUAL DA CONFISSÃO POR DENTRO",
    images: Array.from({ length: 14 }, (_, index) => ({
      src: confissaoImage(`Imagem (${index + 1}).webp`),
      alt: `Página ${index + 1} do Guia Visual da Confissão`,
      width: 600,
      height: 900,
    })),
  },
  benefits: {
    title: "O GUIA VISUAL DA CONFISSÃO POSSUI:",
    ctaText: "QUERO ACESSAR AGORA",
    items: [
      { icon: "⏱️", title: "Mais clareza", desc: "Abra o guia e saiba exatamente o que dizer, sem gaguejar ou esquecer o que precisa confessar." },
      { icon: "🧭", title: "Mais organização", desc: "Siga o exame de consciência organizado por áreas da vida e não esqueça nada importante." },
      { icon: "🙏", title: "Mais tranquilidade", desc: "Saia do confessionário com a certeza de que fez sua parte da forma correta." },
      { icon: "💙", title: "Mais proximidade com Deus", desc: "Sinta mais leveza e conexão espiritual depois de cada confissão." },
    ],
  },
  urgency: {
    pill: "OPORTUNIDADE ÚNICA",
    title: "QUANTAS VEZES VOCÊ NÃO SOUBE COMO SE CONFESSAR DA FORMA CORRETA?",
    highlight: "",
    body: "Você já sabe que precisa se confessar. Falta um passo a passo pronto para organizar o que dizer e sair em paz.",
    ctaText: "QUERO ACESSAR AGORA",
    trust: ["ACESSO IMEDIATO • ACESSO VITALÍCIO"],
  },
  idealPara: {
    pill: "É PARA VOCÊ",
    title: "ESTE GUIA É IDEAL PARA QUEM DESEJA:",
    subtitle: "Mais clareza para se preparar, confessar-se e seguir em paz.",
    items: [
      { icon: "📝", title: "Se preparar", desc: "Organizar um exame de consciência antes de ir ao confessionário." },
      { icon: "🗣️", title: "Saber o que dizer", desc: "Ter frases prontas para iniciar a conversa com o padre com mais segurança." },
      { icon: "🕊️", title: "Confessar-se em paz", desc: "Seguir cada etapa sem medo de esquecer o que é importante." },
      { icon: "🙏", title: "Viver a fé", desc: "Criar uma rotina mais presente de reconciliação e proximidade com Deus." },
    ],
  },
  deliverables: {
    ...laboralOffer.deliverables,
    pill: "ACESSO IMEDIATO",
    title: "TUDO O QUE VOCÊ VAI RECEBER",
    titleHighlight: "",
    imageAlt: "Guia Visual da Confissão",
    image: confissaoImage("Plano Completo.webp"),
    bullets: [
      "Guia visual completo em PDF",
      "Exame de consciência organizado por áreas da vida",
      "Roteiro do que dizer ao padre",
      "Frases para situações de nervosismo",
      "Orientação para depois da confissão",
      "Resumo visual de bolso",
      "Versão para celular e imprimir",
      "E muito mais…",
    ],
  },
  bonusSection: {
    ...laboralOffer.bonusSection,
    pill: "EXTRAS INCLUÍDOS",
    titleLead: "6 BÔNUS",
    titleHighlight: "EXCLUSIVOS",
    subtitle: "No Plano Completo, você recebe materiais extras para se preparar, se confessar e viver com mais profundidade sua vida espiritual.",
    timerText: "BÔNUS DISPONÍVEIS SOMENTE\nNO PLANO COMPLETO",
    cardImageAspect: "portrait",
  },
  bonuses: laboralOffer.bonuses.map((bonus, index) => ({
    ...bonus,
    front: confissaoImage(`bonus-${index + 1}-frente.webp`),
    back: confissaoImage(`bonus-${index + 1}-verso.webp`),
    ...bonuses[index],
  })),
  pricing: {
    titleLead: "ESCOLHA O PLANO",
    titleHighlight: "IDEAL PARA VOCÊ",
    plans: [
      {
        ...laboralOffer.pricing.plans[0],
        title: "Plano Básico",
        image: confissaoImage("Plano Básico.webp"),
        imageAlt: "Plano Básico do Guia Visual da Confissão",
        oldPrice: "De R$37,90",
        price: "R$17,90",
        installments: "ou 4x de R$4,48 no cartão",
        items: [
          "Guia Visual da Confissão em PDF",
          "Arquivo digital em formato visual e prático",
          "Acesso imediato após a confirmação da compra",
          "Material para consultar pelo celular, tablet ou computador",
        ],
        mutedItems: ["Não inclui os bônus do Plano Completo"],
        ctaText: "QUERO O PLANO BÁSICO",
        ctaHref: "#",
      },
      {
        ...laboralOffer.pricing.plans[1],
        title: "Plano Completo",
        image: confissaoImage("Plano Completo.webp"),
        imageAlt: "Plano Completo do Guia Visual da Confissão",
        oldPrice: "De R$199,90",
        price: "R$27,90",
        installments: "ou 6x de R$4,65 no cartão",
        items: [
          "Guia Visual da Confissão em PDF",
          "🎁 Bônus 01: Exame de Consciência de Bolso",
          "🎁 Bônus 02: 40 Perguntas para Preparar sua Confissão",
          "🎁 Bônus 03: Orações para Antes e Depois da Confissão",
          "🎁 Bônus 04: Guia Visual da Primeira Missa Depois da Confissão",
          "🎁 Bônus 05: Calendário de Vida Sacramental",
          "🎁 Bônus 06: Exame Diário de Cinco Minutos",
          "Acesso imediato e vitalício",
        ],
        ctaText: "QUERO O PLANO COMPLETO",
        ctaHref: "#",
      },
    ],
  },
  guarantee: {
    ...laboralOffer.guarantee,
    icon: confissaoImage("garantia-30-dias.webp"),
    iconAlt: "Garantia de 30 dias",
    marqueeText: "GARANTIA 30 DIAS ✦ RISCO ZERO ✦ SATISFAÇÃO OU DINHEIRO DE VOLTA ✦ ",
    marqueeGradient: "linear-gradient(90deg, var(--brand) 0%, var(--brand-deep) 100%)",
    title: "Compra 100% segura e garantida!",
    body: "Você tem **30 dias de garantia** para conhecer o Guia Visual da Confissão. Se o material não fizer sentido para sua preparação ou não atender suas necessidades, você pode solicitar o reembolso dentro desse período. Sem prazo, sem burocracia — o risco fica todo do nosso lado.",
  },
  access: {
    title: "Como você vai receber seu Guia Visual da Confissão",
    steps: [
      { num: "01", title: "Conclua sua compra", desc: "Após o pagamento, seu acesso é liberado automaticamente." },
      { num: "02", title: "Receba no e-mail", desc: "As instruções e o link chegam no e-mail cadastrado na compra." },
      { num: "03", title: "Acesse os PDFs", desc: "Tudo organizado para consultar no celular, tablet ou computador." },
      { num: "04", title: "Prepare-se e confesse-se", desc: "Siga o passo a passo, use as frases prontas e viva sua confissão com clareza." },
    ],
    ctaText: "ACESSAR AGORA",
  },
  faq: {
    title: "Perguntas Frequentes",
    items: [
      { q: "O que acontece quando esqueço um pecado?", a: "Se você esquecer um pecado, a confissão ainda é válida. Apenas mencione-o na próxima confissão." },
      { q: "Preciso repetir pecados que já confessei?", a: "Não é necessário, a não ser que você tenha cometido novamente ou tenha dúvidas sobre a validade." },
      { q: "Posso levar uma anotação?", a: "Sim, é permitido levar anotações para ajudar na organização da confissão." },
      { q: "O padre pode me fazer perguntas?", a: "Sim, o padre pode fazer perguntas para entender melhor sua situação e oferecer orientações." },
      { q: "Como agir quando tenho muita vergonha?", a: "Lembre-se que o padre está lá para te ajudar. Use as frases prontas do guia para iniciar a conversa." },
      { q: "Qual é a diferença entre confissão e direção espiritual?", a: "A confissão é um sacramento para o perdão dos pecados, enquanto a direção espiritual é um acompanhamento mais longo." },
    ],
  },
  footer: {
    ...laboralOffer.footer,
    showUpdate: false,
    copyright: "© Todos os direitos reservados. Este site não é afiliado ao Facebook ou a qualquer entidade do Facebook. Fazemos todos os esforços para indicar claramente as informações do produto. Não vendemos seu e-mail ou dados a terceiros. Dúvidas? Fale conosco de Segunda a Sexta, das 09h às 18h.",
    privacyUrl: "#",
    termsUrl: "#",
    missionText: "Prepare sua confissão com mais clareza, tranquilidade e proximidade com Deus.",
  },
}
