import type { OfferConfig } from '@/types/offer'

export const OFFER: OfferConfig = {
  meta: {
    title: "Pixel Art Bíblico",
    description: "+100 Pixel Artes Bíblicas para colorir e imprimir. Atividades em PDF com personagens bíblicos, ensinamentos e versículos para a criança aprender sobre Deus longe das telas.",
  },
  palette: {
    brand: "#0891B2",
    brandDeep: "#0E7490",
    brandInk: "#164E63",
    brandDark: "#06B6D4",
    brandLight: "#67E8F9",
    brandSubtle: "#ECFEFF",
    cta: "#10B981",
    ctaDeep: "#059669",
    ctaDarkest: "#047857",
    accent: "#F59E0B",
    yellow: "#FBBF24",
    bg: "#FFFFFF",
    bgAlt: "#F0FDFA",
  },
  hero: {
    pill: "PIXEL ART BÍBLICO",
    titleLine1: "Tire seu filho do celular",
    titleLine2: "com +100 Pixel Artes Bíblicas",
    titleLine3: "para colorir e imprimir hoje mesmo.",
    image: "/images/Plano-Completo.webp",
    imageAlt: "Pixel Art Bíblico",
    imageWidth: 340,
    imageHeight: 425,
    subtitle: "Seu filho colore por números, revela personagens bíblicos aos poucos e aprende ensinamentos, versículos e valores cristãos longe das telas.",
    ctaText: "QUERO O PIXEL ART BÍBLICO",
    timerLabel: "BÔNUS ENCERRAM EM",
    marqueeText: "+100 Pixel Artes Bíblicas • PDF A4 Pronto para Imprimir • Acesso Imediato • ",
    marqueeGradient: "linear-gradient(135deg, #67E8F9 0%, #0891B2 55%, #0E7490 100%)",
  },
  socialProof: {
    testimonials: [
      { src: "/images/CR-NINJA-15.webp", alt: "Depoimento 1", gradient: "linear-gradient(90deg, #0891B2, #0E7490)" },
      { src: "/images/CR-NINJA-16.webp", alt: "Depoimento 2", gradient: "linear-gradient(90deg, #10B981, #059669)" },
      { src: "/images/CR-NINJA-17.webp", alt: "Depoimento 3", gradient: "linear-gradient(90deg, #67E8F9, #0891B2)" },
      { src: "/images/CR-NINJA-18.webp", alt: "Depoimento 4", gradient: "linear-gradient(90deg, #0E7490, #164E63)" },
      { src: "/images/CR-NINJA-15.webp", alt: "Depoimento 5", gradient: "linear-gradient(90deg, #10B981, #34D399)" },
      { src: "/images/CR-NINJA-16.webp", alt: "Depoimento 6", gradient: "linear-gradient(90deg, #0891B2, #67E8F9)" },
    ],
  },
  counter: {
    prefix: "+ de",
    target: 100,
    label: "Pixel Artes Bíblicas para colorir",
  },
  kitCards: {
    heading1: "Veja as artes bíblicas que vão tirar seu filho do celular e Ensinar Valores Bíblicos",
    images: [
      { src: "/images/Página 99.webp", alt: "Pixel Art Bíblico - Página 99" },
      { src: "/images/Página 97.webp", alt: "Pixel Art Bíblico - Página 97" },
      { src: "/images/Página 94.webp", alt: "Pixel Art Bíblico - Página 94" },
      { src: "/images/Página 80.webp", alt: "Pixel Art Bíblico - Página 80" },
      { src: "/images/Página 62.webp", alt: "Pixel Art Bíblico - Página 62" },
      { src: "/images/Página 59.webp", alt: "Pixel Art Bíblico - Página 59" },
      { src: "/images/Página 46.webp", alt: "Pixel Art Bíblico - Página 46" },
      { src: "/images/Página 25.webp", alt: "Pixel Art Bíblico - Página 25" },
      { src: "/images/Página 11.webp", alt: "Pixel Art Bíblico - Página 11" },
      { src: "/images/Página 10.webp", alt: "Pixel Art Bíblico - Página 10" },
    ],
  },
  benefits: [
    { icon: "📱", title: "Menos tempo no celular", desc: "Em vez de dizer 'larga o celular', você oferece uma alternativa pronta, visual e divertida." },
    { icon: "🎯", title: "Mais foco e concentração", desc: "A criança segue os números e pinta os quadradinhos, estimulando atenção, paciência e concentração." },
    { icon: "📖", title: "Aprendizado bíblico leve", desc: "Ensina sobre Deus sem ser pesado. As Pixel Artes apresentam personagens, versículos e valores de forma simples." },
    { icon: "✏️", title: "Praticidade para a mãe", desc: "Você não precisa preparar nada. Basta escolher uma arte, imprimir em A4 e entregar para a criança." },
    { icon: "🧠", title: "Criatividade e coordenação", desc: "Pintar por números trabalha coordenação motora, percepção visual, noção de cores e organização." },
    { icon: "🙏", title: "Valores cristãos na rotina", desc: "Cada momento longe da tela vira oportunidade para falar sobre fé, amor e confiança em Deus." },
  ],
  urgency: {
    pill: "OPORTUNIDADE ÚNICA",
    title: "Comece hoje a tirar\nseu filho do celular\ncom o",
    highlight: "Pixel Art Bíblico",
    body: "",
    ctaText: "QUERO O PIXEL ART BÍBLICO",
    trust: ["ACESSO IMEDIATO • ACESSO VITALÍCIO"],
  },
  idealPara: {
    pill: "É PARA VOCÊ",
    title: "Ideal para você que quer",
    subtitle: "Este Pixel Art Bíblico foi pensado para mães cristãs que querem ocupar os filhos com atividades saudáveis e com propósito.",
    items: [
      { icon: "📱", title: "Tirar seu filho do celular sem brigar", desc: "Você entrega uma alternativa pronta, divertida e bíblica para a criança se concentrar longe da tela." },
      { icon: "⏱️", title: "Ter uma atividade cristã pronta para usar", desc: "O material vem pronto para imprimir. Você escolhe uma arte e entrega para a criança começar." },
      { icon: "📖", title: "Ensinar sobre Deus de um jeito leve", desc: "A criança colore por números e descobre personagens bíblicos com ensinamentos e versículos." },
      { icon: "🏠", title: "Criar momentos mais tranquilos em casa", desc: "Quando a criança pede o celular, você imprime uma Pixel Arte e transforma o tédio em um momento criativo." },
      { icon: "🌱", title: "Plantar valores cristãos desde cedo", desc: "Cada arte aproxima a criança de valores como fé, obediência, coragem, amor e confiança em Deus." },
      { icon: "🙏", title: "Colocar mais fé na rotina da criança", desc: "Enquanto colore, seu filho entra em contato com valores cristãos de forma natural." },
    ],
  },
  deliverables: {
    pill: "CONTEÚDO DO KIT",
    title: "Tudo o que você vai receber",
    titleHighlight: "Pixel Art Bíblico",
    image: "/images/Plano-Completo.webp",
    imageAlt: "Pixel Art Bíblico",
    bullets: [
      "+100 Pixel Artes Bíblicas para colorir",
      "PDF A4 pronto para imprimir em casa",
      "Legenda de cores por números",
      "Artes do Antigo e Novo Testamento",
      "Personagens bíblicos, discípulos e mulheres da Bíblia",
      "Artes por valores cristãos: fé, obediência, coragem, amor",
      "Ensinamentos e versículos em cada atividade",
      "Diferentes níveis de dificuldade",
      "Dicas de uso para tornar o momento mais divertido",
    ],
  },
  bonusSection: {
    pill: "EXTRA INCLUÍDO",
    titleLead: "6 BÔNUS",
    titleHighlight: "EXCLUSIVOS",
    subtitle: "Ao adquirir hoje, você também recebe **6 materiais complementares** para o aprendizado do seu filho.",
    cardLabel: "BÔNUS",
    touchHint: "Toque na imagem acima para ver o conteúdo.",
    backHint: "Toque para voltar",
    timerText: "OFERTA EXPIRA COM O CRONÔMETRO",
    freeLabel: "GRÁTIS",
  },
  bonuses: [
    {
      front: "/images/CR-NINJA-15.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_26_00.webp",
      title: "Mapas Mentais do Antigo Testamento",
      desc: "Guia visual e lúdico para ajudar a criança a entender os principais livros, histórias e personagens do Antigo Testamento.",
      price: "R$ 27,90",
    },
    {
      front: "/images/CR-NINJA-16.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_56-1.webp",
      title: "Mapas Mentais do Novo Testamento",
      desc: "Guia visual para facilitar o aprendizado sobre Jesus, os evangelhos, os apóstolos e os ensinamentos do Novo Testamento.",
      price: "R$ 27,90",
    },
    {
      front: "/images/CR-NINJA-17.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_52-1.webp",
      title: "Colorir com os Salmos",
      desc: "Desenhos para colorir com mensagens inspiradas nos Salmos, ajudando a criança a aprender sobre confiança, gratidão e amor de Deus.",
      price: "R$ 19,90",
    },
    {
      front: "/images/CR-NINJA-18.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_33.webp",
      title: "Colorir com os Provérbios",
      desc: "Desenhos para colorir com mensagens de Provérbios, ensinando sobre sabedoria, obediência, respeito e boas escolhas.",
      price: "R$ 19,90",
    },
    {
      front: "/images/CR-NINJA-15.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_44-1.webp",
      title: "Planner de Leitura Bíblica",
      desc: "Checklist e cronograma organizado mês a mês para acompanhar a leitura bíblica com mais clareza.",
      price: "R$ 37,90",
    },
    {
      front: "/images/CR-NINJA-16.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_48-1.webp",
      title: "Marcadores de Abas Bíblicas",
      desc: "Marcadores práticos, coloridos e bonitos para organizar a Bíblia e encontrar os livros com mais facilidade.",
      price: "R$ 47,90",
    },
  ],
  pricing: {
    titleLead: "ESCOLHA SUA",
    titleHighlight: "OPÇÃO",
    plans: [
      {
        id: "basic",
        label: "PARA COMEÇAR HOJE",
        title: "Plano Básico",
        image: "/images/Plano-Completo.webp",
        imageAlt: "Plano Básico",
        featured: false,
        oldPrice: "de R$ 39,90",
        price: "R$ 17,90",
        installments: "ou 4x de R$ 4,47 no cartão",
        items: [
          "+100 Pixel Artes Bíblicas para colorir",
          "PDF A4 pronto para imprimir",
          "Acesso imediato após a compra",
        ],
        ctaText: "QUERO O PLANO BÁSICO",
        ctaHref: "#",
      },
      {
        id: "premium",
        title: "Plano Completo",
        image: "/images/Plano-Completo.webp",
        imageAlt: "Plano Completo",
        featured: true,
        badgeText: "MAIS VENDIDO",
        oldPrice: "de R$ 221,30",
        price: "R$ 27,90",
        installments: "ou 4x de R$ 6,97 no cartão",
        items: [
          "+100 Pixel Artes Bíblicas para colorir",
          "PDF A4 pronto para imprimir",
          "Mapas Mentais do Antigo Testamento",
          "Mapas Mentais do Novo Testamento",
          "Livro de Colorir com Ensinamentos dos Salmos",
          "Livro de Colorir com Ensinamentos dos Provérbios",
          "Planner de Leitura Bíblica",
          "Marcadores de Abas Bíblicas",
          "Acesso vitalício ao material",
          "Envio imediato por e-mail",
        ],
        ctaText: "QUERO O PLANO COMPLETO",
        ctaHref: "#",
      },
    ],
  },
  guarantee: {
    marqueeText: "GARANTIA 7 DIAS • SATISFAÇÃO GARANTIDA • DINHEIRO DE VOLTA • ",
    marqueeGradient: "linear-gradient(135deg, #67E8F9 0%, #0891B2 55%, #0E7490 100%)",
    icon: "/images/INCONDICIONAL-_1_-1-1.webp",
    iconAlt: "Garantia de 7 dias",
    title: "Satisfação garantida\nou seu dinheiro de volta.",
    body: "Teste o **Pixel Art Bíblico** por 7 dias. Se não gostar, devolvemos 100% do valor, sem perguntas.",
  },
  access: {
    title: "Como você recebe e usa o Pixel Art Bíblico",
    steps: [
      { num: "01", title: "Conclua sua compra", desc: "Após o pagamento, seu acesso é liberado automaticamente." },
      { num: "02", title: "Receba no seu e-mail", desc: "As instruções de acesso chegam diretamente no e-mail cadastrado." },
      { num: "03", title: "Baixe os PDFs", desc: "Acesse o material e baixe as +100 Pixel Artes, tudo organizado." },
      { num: "04", title: "Imprima e use", desc: "Escolha uma arte, imprima em A4 e entregue para seu filho colorir." },
    ],
  },
  faq: {
    title: "Perguntas Frequentes",
    items: [
      { q: "O Pixel Art Bíblico é físico ou digital?", a: "É 100% digital. Após a compra, você recebe o acesso por e-mail e pode imprimir em casa, na igreja ou em uma gráfica." },
      { q: "Como recebo o material depois da compra?", a: "Após a confirmação do pagamento, você recebe as instruções de acesso no e-mail cadastrado." },
      { q: "Preciso pagar frete?", a: "Não. Como o material é digital, não há frete nem espera. Você compra e já pode usar." },
      { q: "Para qual idade é indicado?", a: "O material é ideal para crianças de 4 a 8 anos, com níveis de dificuldade variados." },
      { q: "Meu filho vai conseguir colorir sozinho?", a: "Sim. A criança segue a legenda de cores e pinta os números. Crianças menores podem precisar de ajuda no começo." },
      { q: "O que vem dentro do Pixel Art Bíblico?", a: "+100 Pixel Artes em PDF com personagens bíblicos, pintura por números, legenda de cores, ensinamentos e versículos. No Plano Completo, você também recebe todos os bônus." },
      { q: "Posso imprimir mais de uma vez?", a: "Sim. Depois de baixar, você pode imprimir sempre que quiser para uso pessoal da sua família." },
      { q: "E se eu não gostar do material?", a: "Você tem 7 dias de garantia para testar. Se não gostar, devolvemos 100% do valor." },
      { q: "Preciso saber mexer em algum programa?", a: "Não. Basta acessar o PDF, baixar e imprimir. A criança também não precisa de telas." },
      { q: "Qual plano vale mais a pena?", a: "O Plano Completo. Por apenas R$ 10 a mais, você leva todos os 6 bônus." },
    ],
  },
  footer: {
    updateTitle: "Material em constante atualização",
    updateBody: "O Pixel Art Bíblico recebe novas artes periodicamente. Ao adquirir agora, você garante acesso vitalício e todas as atualizações futuras.",
    copyright: "2026 © Todos os direitos reservados. Este material é protegido pela Lei nº 9.610/98, sendo proibida a reprodução total ou parcial sem autorização.",
    privacyUrl: "#",
    termsUrl: "#",
  },
}
