import type { OfferConfig } from '@/types/offer'

export const OFFER: OfferConfig = {
  meta: {
    title: "Pixel Art Bíblico – Atividades bíblicas para tirar seu filho do celular",
    description: "+100 Pixel Artes Bíblicas para colorir e imprimir. Atividades em PDF com personagens bíblicos, ensinamentos e versículos para a criança aprender sobre Deus longe das telas.",
  },
  palette: {
    brand: "#0B7FE8",
    brandDeep: "#082F63",
    brandInk: "#123A6D",
    brandDark: "#1D4ED8",
    brandLight: "#49A6FF",
    brandSubtle: "#EAF5FF",
    cta: "#22C978",
    ctaDeep: "#00A85A",
    ctaDarkest: "#007D43",
    accent: "#FF8A5B",
    yellow: "#FFD166",
    bg: "#FFFFFF",
    bgAlt: "#F5F8FF",
  },
  hero: {
    pill: "PIXEL ART BÍBLICO",
    titleLine1: "Tire seu filho do celular",
    titleLine2: "com +100 Pixel Artes Bíblicas",
    titleLine3: "para colorir e imprimir hoje mesmo.",
    image: "/images/a4996fc9-5b06-464a-86b1-817af5b4f1ae.webp",
    imageAlt: "Pixel Art Bíblico",
    imageWidth: 340,
    imageHeight: 425,
    subtitle: "Com o Pixel Art Bíblico, seu filho colore por números, revela personagens bíblicos aos poucos e aprende ensinamentos, versículos e valores cristãos longe das telas.",
    ctaText: "QUERO O PIXEL ARTE BÍBLICO",
    timerLabel: "BÔNUS ENCERRAM EM",
    marqueeText: "+100 Pixel Artes Bíblicas • PDF A4 Pronto para Imprimir • Acesso Imediato • ",
    marqueeGradient: "linear-gradient(135deg, #93C5FD 0%, #0B7FE8 55%, #1D4ED8 100%)",
    bullets: [
      "+100 Pixel Artes Bíblicas para colorir",
      "Artes em PDF A4 prontas para imprimir",
      "Pixel Art por números com personagens bíblicos",
      "Aprende Ensinamentos, Versículos e Valores Bíblicos",
      "Ajuda a ocupar a criança com propósito, sem depender do celular",
    ],
  },
  socialProof: {
    testimonials: [
      { src: "/images/CR-NINJA-15.webp", alt: "Depoimento 1", gradient: "linear-gradient(90deg, #0B7FE8, #1D4ED8)" },
      { src: "/images/CR-NINJA-16.webp", alt: "Depoimento 2", gradient: "linear-gradient(90deg, #22C978, #1AAF64)" },
      { src: "/images/CR-NINJA-17.webp", alt: "Depoimento 3", gradient: "linear-gradient(90deg, #49A6FF, #0B7FE8)" },
      { src: "/images/CR-NINJA-18.webp", alt: "Depoimento 4", gradient: "linear-gradient(90deg, #082F63, #1D4ED8)" },
      { src: "/images/CR-NINJA-15.webp", alt: "Depoimento 5", gradient: "linear-gradient(90deg, #22C978, #4ADE80)" },
      { src: "/images/CR-NINJA-16.webp", alt: "Depoimento 6", gradient: "linear-gradient(90deg, #0B7FE8, #49A6FF)" },
    ],
  },
  counter: {
    prefix: "+ de",
    target: 100,
    label: "Pixel Artes Bíblicas para colorir",
  },
  kitCards: {
    heading1: "Veja as artes bíblicas que vão tirar seu filho do celular e Ensinar Valores Bíblicos",
    heading2: "Dentro do Pixel Art Bíblico, você encontra +100 artes bíblicas para ocupar seu filho longe do celular enquanto ele aprende histórias dos personagens e valores da Bíblia.",
    images: [
      { src: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_26_00.webp", alt: "Pixel Art Bíblico - Amostra 1" },
      { src: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_56-1.webp", alt: "Pixel Art Bíblico - Amostra 2" },
      { src: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_52-1.webp", alt: "Pixel Art Bíblico - Amostra 3" },
      { src: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_33.webp", alt: "Pixel Art Bíblico - Amostra 4" },
      { src: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_44-1.webp", alt: "Pixel Art Bíblico - Amostra 5" },
      { src: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_48-1.webp", alt: "Pixel Art Bíblico - Amostra 6" },
      { src: "/images/2dd43d5e-6d02-4303-b0f8-be047df9bb0c.webp", alt: "Pixel Art Bíblico - Amostra 7" },
      { src: "/images/7886b7ae-8c1b-49a2-b185-e4955ab73050.webp", alt: "Pixel Art Bíblico - Amostra 8" },
    ],
  },
  benefits: [
    { icon: "📱", title: "Menos tempo no celular", desc: "Ajuda a tirar a criança da tela sem transformar isso em uma briga. Em vez de apenas dizer 'larga o celular', você oferece uma alternativa pronta, visual e divertida." },
    { icon: "🎯", title: "Mais foco e concentração", desc: "A criança se envolve para descobrir a imagem final. Como ela precisa seguir os números e pintar os quadradinhos, a atividade estimula atenção, paciência e concentração." },
    { icon: "📖", title: "Aprendizado bíblico leve", desc: "Ensina sobre Deus sem parecer uma aula pesada. As Pixel Artes ajudam a apresentar personagens, versículos e valores cristãos de forma simples e visual para a criança entender." },
    { icon: "✏️", title: "Praticidade para a mãe", desc: "Você não precisa preparar nada. Basta escolher uma das +100 Pixel Artes, imprimir em folha A4 e entregar para a criança começar a colorir." },
    { icon: "🧠", title: "Criatividade e coordenação", desc: "Ao pintar por números, a criança trabalha coordenação motora, percepção visual, noção de cores e organização enquanto se diverte." },
    { icon: "🙏", title: "Valores cristãos na rotina", desc: "Cada momento longe da tela pode se tornar uma oportunidade para falar sobre fé, amor, obediência, coragem e confiança em Deus." },
  ],
  urgency: {
    pill: "OPORTUNIDADE ÚNICA",
    title: "Comece hoje a tirar\nseu filho do celular\ncom",
    highlight: "+100 Pixel Artes Bíblicas",
    body: "Mais um dia vendo seu filho preso no celular pode parecer normal… mas no fundo você sabe que ele poderia estar usando esse tempo de um jeito melhor.\n\nCom o Pixel Art Bíblico, você entrega uma alternativa pronta: +100 Pixel Artes por números para colorir, onde a criança segue as cores, revela personagens bíblicos e aprende valores cristãos.\n\nVocê imprime em poucos minutos. Ele colore longe da tela. E o tempo livre ganha mais propósito.",
    ctaText: "QUERO O PIXEL ARTE BÍBLICO",
    trust: ["ACESSO IMEDIATO", "ACESSO VITALÍCIO"],
  },
  idealPara: {
    pill: "É PARA VOCÊ",
    title: "Ideal para você que deseja",
    subtitle: "Este Pixel Art Bíblico foi pensado para mães cristãs que querem ocupar os filhos com atividades saudáveis, criativas e com propósito.",
    items: [
      { icon: "📱", title: "Tirar seu filho do celular sem brigar", desc: "Você entrega uma alternativa pronta, visual, divertida e bíblica para a criança se concentrar longe da tela com propósito." },
      { icon: "⏱️", title: "Ter uma atividade cristã pronta para usar", desc: "O material vem pronto para imprimir. Você escolhe uma arte, separa os lápis de cor e entrega para a criança começar." },
      { icon: "📖", title: "Ensinar sobre Deus de um jeito leve", desc: "A criança colore por números, descobre os personagens bíblicos e entra em contato com ensinamentos e versículos sem parecer chato." },
      { icon: "🏠", title: "Criar momentos mais tranquilos em casa", desc: "Quando a criança está entediada e pede o celular, você imprime uma Pixel Arte e transforma esse tempo em um momento calmo e criativo." },
      { icon: "🌱", title: "Plantar valores cristãos desde cedo", desc: "Cada arte ajuda a aproximar a criança de personagens e valores da Bíblia, como fé, obediência, coragem, amor e confiança em Deus." },
      { icon: "🙏", title: "Colocar mais fé na rotina da criança", desc: "Enquanto colore, seu filho entra em contato com valores cristãos de forma natural e divertida." },
    ],
  },
  deliverables: {
    pill: "CONTEÚDO DO KIT",
    title: "Tudo o que você vai receber",
    titleHighlight: "Pixel Art Bíblico",
    image: "/images/a4996fc9-5b06-464a-86b1-817af5b4f1ae.webp",
    imageAlt: "Pixel Art Bíblico",
    bullets: [
      "+100 Pixel Artes Bíblicas para colorir",
      "PDF A4 pronto para imprimir",
      "Como usar o Pixel Art Bíblico + Dicas",
      "Legenda de cores por números",
      "Pixel Artes do Antigo Testamento",
      "Pixel Artes do Novo Testamento",
      "Pixel Artes dos Personagens bíblicos",
      "Pixel Artes dos Valores Bíblicos",
      "Pixel Artes dos discípulos de Jesus",
      "Pixel Artes das Mulheres da Bíblia",
      "Ensinamentos e Versículos Bíblicos",
      "Artes separadas por temas e personagens",
      "Diferentes níveis de dificuldade",
    ],
  },
  bonusSection: {
    pill: "EXTRA INCLUÍDO",
    titleLead: "6 BÔNUS",
    titleHighlight: "EXCLUSIVOS",
    subtitle: "Ao adquirir hoje, você também recebe **6 materiais complementares** para deixar o aprendizado do seu filho ainda mais completo e divertido.",
    cardLabel: "BÔNUS",
    touchHint: "Toque na imagem acima para ver o conteúdo.",
    backHint: "Toque para voltar",
    timerText: "OFERTA EXPIRA COM O CRONÔMETRO",
    freeLabel: "GRÁTIS",
  },
  bonuses: [
    {
      front: "/images/CR-NINJA-15.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_26_00.webp",
      title: "Mapas Mentais do Antigo Testamento",
      desc: "Guia visual e lúdico para ajudar a criança a entender os principais livros, histórias e personagens do Antigo Testamento.",
      price: "R$ 27,90",
    },
    {
      front: "/images/CR-NINJA-16.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_56-1.webp",
      title: "Mapas Mentais do Novo Testamento",
      desc: "Guia visual para facilitar o aprendizado sobre Jesus, os evangelhos, os apóstolos e os ensinamentos do Novo Testamento.",
      price: "R$ 27,90",
    },
    {
      front: "/images/CR-NINJA-17.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_52-1.webp",
      title: "Colorir com os Salmos",
      desc: "Desenhos para colorir com mensagens inspiradas nos Salmos, ajudando a criança a aprender sobre confiança, gratidão e amor de Deus.",
      price: "R$ 27,90",
    },
    {
      front: "/images/CR-NINJA-18.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_33.webp",
      title: "Colorir com os Provérbios",
      desc: "Desenhos para colorir com mensagens de Provérbios, ensinando sobre sabedoria, obediência, respeito e boas escolhas.",
      price: "R$ 27,90",
    },
    {
      front: "/images/CR-NINJA-15.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_44-1.webp",
      title: "Planner de Leitura Bíblica",
      desc: "Checklist e cronograma organizado mês a mês para acompanhar a leitura bíblica com mais clareza.",
      price: "R$ 27,90",
    },
    {
      front: "/images/CR-NINJA-16.webp",
      back: "/images/ChatGPT-Image-21-de-mai.-de-2026-14_25_48-1.webp",
      title: "Marcadores de Abas Bíblicas",
      desc: "Marcadores práticos, coloridos e bonitos para organizar a Bíblia e encontrar os livros com mais facilidade.",
      price: "R$ 27,90",
    },
  ],
  pricing: {
    titleLead: "ESCOLHA SUA",
    titleHighlight: "OPÇÃO",
    plans: [
      {
        id: "basic",
        label: "PARA COMEÇAR HOJE",
        title: "Plano Básico",
        image: "/images/4943e9df-5a44-4443-b18d-b7084546bdad.webp",
        imageAlt: "Plano Básico",
        featured: false,
        oldPrice: "de R$ 39,90",
        price: "R$ 17,90",
        installments: "ou 4x de R$ 4,47 no cartão",
        items: [
          "+100 Pixel Artes Bíblicas para colorir",
          "PDF A4 pronto para imprimir",
          "Acesso imediato após a compra",
        ],
        ctaText: "QUERO O PLANO BÁSICO",
        ctaHref: "#",
      },
      {
        id: "premium",
        title: "Plano Completo",
        image: "/images/a4996fc9-5b06-464a-86b1-817af5b4f1ae.webp",
        imageAlt: "Plano Completo",
        featured: true,
        badgeText: "MAIS VENDIDO",
        oldPrice: "de R$ 59,90",
        price: "R$ 27,90",
        installments: "ou 4x de R$ 6,97 no cartão",
        items: [
          "+100 Pixel Artes Bíblicas para colorir",
          "PDF A4 pronto para imprimir",
          "Mapas Mentais do Antigo Testamento",
          "Mapas Mentais do Novo Testamento",
          "Livro de Colorir com Ensinamentos dos Salmos",
          "Livro de Colorir com Ensinamentos dos Provérbios",
          "Planner de Leitura Bíblica",
          "Marcadores de Abas Bíblicas",
          "Acesso vitalício ao material",
          "Envio imediato por e-mail",
        ],
        ctaText: "QUERO O PLANO COMPLETO",
        ctaHref: "#",
      },
    ],
  },
  guarantee: {
    marqueeText: "GARANTIA 7 DIAS • SATISFAÇÃO GARANTIDA • DINHEIRO DE VOLTA • ",
    marqueeGradient: "linear-gradient(135deg, #93C5FD 0%, #0B7FE8 55%, #1D4ED8 100%)",
    icon: "/images/INCONDICIONAL-_1_-1-1.webp",
    iconAlt: "Garantia de 7 dias",
    title: "Satisfação garantida\nou seu dinheiro de volta.",
    body: "Teste o **Pixel Art Bíblico** por 7 dias. Se você não gostar por algum motivo, devolvemos 100% do valor, sem perguntas.",
  },
  access: {
    title: "Como você recebe e usa o Pixel Art Bíblico",
    steps: [
      { num: "01", title: "Conclua sua compra", desc: "Após o pagamento, seu acesso ao Pixel Art Bíblico é liberado automaticamente." },
      { num: "02", title: "Receba no seu e-mail", desc: "Você recebe as instruções de acesso diretamente no e-mail cadastrado na compra." },
      { num: "03", title: "Baixe os PDFs", desc: "Acesse o material e baixe as +100 Pixel Artes Bíblicas para colorir. Tudo organizado para facilitar o uso." },
      { num: "04", title: "Imprima e use", desc: "Escolha uma Pixel Arte, imprima em folha A4 e entregue para seu filho colorir por números e aprender sobre Deus." },
    ],
  },
  faq: {
    title: "Perguntas Frequentes",
    items: [
      { q: "O Pixel Art Bíblico é físico ou digital?", a: "É 100% digital. Após a compra, você recebe o acesso por e-mail, baixa os arquivos em PDF e pode imprimir em casa, na escola, na igreja ou em uma gráfica." },
      { q: "Como recebo o material depois da compra?", a: "Após a confirmação do pagamento, você recebe as instruções de acesso no e-mail cadastrado. É só abrir, acessar o material, baixar os PDFs e imprimir." },
      { q: "Preciso pagar frete?", a: "Não. Como o material é digital, você não paga frete e não precisa esperar nada pelos Correios. Você compra, recebe por e-mail e já pode começar a usar." },
      { q: "Para qual idade é indicado?", a: "O material é ideal para crianças de 4 a 8 anos. As artes têm diferentes níveis de dificuldade, então você pode escolher de acordo com a idade da criança." },
      { q: "Meu filho vai conseguir colorir sozinho?", a: "Sim. As Pixel Artes funcionam por números: a criança olha a legenda de cores, pinta os quadradinhos correspondentes e descobre a imagem aos poucos. Crianças menores podem precisar de ajuda no começo." },
      { q: "O que vem dentro do Pixel Art Bíblico?", a: "Você recebe +100 Pixel Artes Bíblicas para colorir em PDF. As artes incluem personagens bíblicos, pintura por números, legenda de cores, ensinamentos cristãos e versículos relacionados. No Plano Completo, você também recebe todos os bônus." },
      { q: "Posso imprimir mais de uma vez?", a: "Sim. Depois de baixar, você pode imprimir sempre que quiser para uso pessoal da sua família, igreja ou EBD. Assim você sempre terá uma opção pronta quando a criança pedir o celular." },
      { q: "E se eu não gostar do material?", a: "Você tem 7 dias de garantia para testar. Se sentir que o Pixel Art Bíblico não é para sua família, pode solicitar o reembolso dentro do prazo." },
      { q: "Preciso saber mexer em algum programa?", a: "Não. Você só precisa acessar o PDF, baixar e imprimir. A criança também não precisa usar celular, tablet ou computador para fazer as atividades." },
      { q: "Qual plano vale mais a pena?", a: "O Plano Completo é o mais recomendado. Além das +100 Pixel Artes, ele inclui os 6 bônus. Por apenas R$ 10 a mais que o Plano Básico, você recebe um kit muito mais completo." },
    ],
  },
  footer: {
    updateTitle: "Material em constante atualização",
    updateBody: "O Pixel Art Bíblico recebe novas artes periodicamente. Ao adquirir agora, você garante acesso vitalício e todas as atualizações futuras sem pagar nada a mais.",
    copyright: "2026 © Todos os direitos reservados. Este material é protegido pela Lei nº 9.610/98, sendo proibida a reprodução total ou parcial sem autorização.",
    privacyUrl: "#",
    termsUrl: "#",
  },
}
