import type { OfferConfig } from '@/types/offer'

export const OFFER: OfferConfig = {
  meta: {
    title: "50 Modelos de Lembrancinhas para Crisma",
    description: "50 modelos de lembrancinhas para Crisma prontas para imprimir, organizadas por temas com mensagens de fé, versículos e símbolos católicos.",
  },
  palette: {
    brand: "#2A4A6B",
    brandDeep: "#1E3A52",
    brandInk: "#142838",
    brandDark: "#3E6A94",
    brandLight: "#A8C5DE",
    brandSubtle: "#EDF3F8",
    cta: "#D47A5A",
    ctaDeep: "#B86040",
    ctaDarkest: "#8C4428",
    accent: "#E8927C",
    yellow: "#F5D76E",
    bg: "#FFFFFF",
    bgAlt: "#FDF6ED",
  },
  hero: {
    pill: "LEMBRANCINHAS CRISTÃ",
    titleLine1: "+50 Modelos Exclusivos de Lembrancinhas para Crisma",
    titleLine2: "",
    titleLine3: "Organizadas por temas, prontas para imprimir e entregar.",
    image: "/images/plano-completo.webp",
    imageAlt: "Lembrancinhas para Crisma",
    imageWidth: 340,
    imageHeight: 425,
    subtitle: "Prontas para imprimir, fáceis de montar e organizadas por temas para você produzir e entregar ao crismando sem precisar criar nada do zero.",
    ctaText: "QUERO AS LEMBRANCINHAS",
    timerLabel: "BÔNUS ENCERRAM EM",
    marqueeText: "+50 MODELOS ☆ ACESSO IMEDIATO ☆ ALTA QUALIDADE ☆ ",
    marqueeGradient: "linear-gradient(135deg, #A8C5DE 0%, #2A4A6B 55%, #1E3A52 100%)",
    bullets: [],
  },
  socialProof: {
    title: "Catequistas como você já aprovaram",
    testimonials: [
      { src: "/images/depoimento-1.webp", alt: "Depoimento 1", gradient: "linear-gradient(90deg, #2A4A6B, #1E3A52)" },
      { src: "/images/depoimento-2.webp", alt: "Depoimento 2", gradient: "linear-gradient(90deg, #D47A5A, #B86040)" },
      { src: "/images/depoimento-3.webp", alt: "Depoimento 3", gradient: "linear-gradient(90deg, #A8C5DE, #2A4A6B)" },
      { src: "/images/depoimento-4.webp", alt: "Depoimento 4", gradient: "linear-gradient(90deg, #1E3A52, #142838)" },
      { src: "/images/depoimento-5.webp", alt: "Depoimento 5", gradient: "linear-gradient(90deg, #D47A5A, #E8927C)" },
    ],
  },
  counter: {
    prefix: "+ de",
    target: 50,
    label: "Modelos de Lembrancinhas para Crisma",
  },
  kitCards: {
    heading1: "Veja como são os modelos que você vai receber:",
    images: [
      { src: "/images/pagina-99.webp", alt: "Lembrancinha para Crisma 1" },
      { src: "/images/pagina-97.webp", alt: "Lembrancinha para Crisma 2" },
      { src: "/images/pagina-94.webp", alt: "Lembrancinha para Crisma 3" },
      { src: "/images/pagina-80.webp", alt: "Lembrancinha para Crisma 4" },
      { src: "/images/pagina-62.webp", alt: "Lembrancinha para Crisma 5" },
      { src: "/images/pagina-59.webp", alt: "Lembrancinha para Crisma 6" },
      { src: "/images/pagina-46.webp", alt: "Lembrancinha para Crisma 7" },
      { src: "/images/pagina-25.webp", alt: "Lembrancinha para Crisma 8" },
      { src: "/images/pagina-11.webp", alt: "Lembrancinha para Crisma 9" },
      { src: "/images/pagina-10.webp", alt: "Lembrancinha para Crisma 10" },
    ],
  },
  benefits: {
    title: "Deixe a caminhada da Crisma mais especial\ncom lembrancinhas de Fé e Propósito",
    ctaText: "QUERO AS LEMBRANCINHAS",
    items: [
      { icon: "⏱️", title: "Praticidade", desc: "50 modelos prontos, você baixa, imprime e entrega em menos de 10 minutos." },
      { icon: "📋", title: "Variedade", desc: "Cada tema já tem sua lembrancinha: Cura, Espírito Santo, Fé, Apóstolos, Gratidão e mais." },
      { icon: "💝", title: "Impacto", desc: "Uma lembrancinha bonita transforma um encontro comum em um momento que o crismando guarda." },
      { icon: "🙏", title: "Propósito", desc: "Você não entrega só papel, entrega uma mensagem de fé que marca o coração de um jovem." },
    ],
  },
  urgency: {
    pill: "OPORTUNIDADE ÚNICA",
    title: "Deixe cada encontro mais especial\ncom uma lembrancinha de fé\npronta para entregar",
    highlight: "",
    body: "Enquanto você pensa, outras catequistas já estão baixando os modelos. O preço promocional não dura para sempre.",
    ctaText: "QUERO AS LEMBRANCINHAS",
    trust: ["ACESSO IMEDIATO • ACESSO VITALÍCIO"],
  },
  idealPara: {
    pill: "É PARA VOCÊ",
    title: "Ideal para você que deseja",
    subtitle: "Feito para catequistas e coordenadoras que querem encontros mais bonitos sem perder tempo.",
    items: [
      { icon: "📋", title: "Praticidade", desc: "Ter uma lembrancinha pronta sem precisar criar nada do zero" },
      { icon: "💡", title: "Variedade", desc: "Ter modelos para cada tema da Crisma sem repetir" },
      { icon: "💝", title: "Recordação", desc: "Entregar algo que o crismando leva para casa e guarda" },
      { icon: "🙏", title: "Fé e Propósito", desc: "Transmitir mensagens que fazem sentido na caminhada de fé" },
    ],
  },
  deliverables: {
    pill: "CONTEÚDO DO KIT",
    title: "Tudo o que você vai receber\nao adquirir",
    titleHighlight: "50 Modelos de Lembrancinhas para Crisma",
    image: "/images/plano-completo.webp",
    imageAlt: "Lembrancinhas para Crisma",
    bullets: [
      "50 modelos organizados por temas da Crisma",
      "Lembrancinhas de Cura, Espírito Santo, Fé, Apóstolos, Gratidão, Propósito, Oração e mais",
      "Modelos com mensagens, versículos e símbolos católicos",
      "Material em PDF, baixe, imprima e use no próximo encontro",
      "Modelos com espaço para doces, brindes e lembranças",
      "E muito mais…",
    ],
  },
  bonusSection: {
    pill: "EXTRA INCLUÍDO",
    titleLead: "6 BÔNUS",
    titleHighlight: "EXCLUSIVOS",
    subtitle: "Ao adquirir o Plano Completo você também\nrecebe 6 bônus especiais",
    cardLabel: "BÔNUS",
    touchHint: "Toque na imagem acima para ver o conteúdo.",
    backHint: "Toque para voltar",
    timerText: "BÔNUS DISPONÍVEIS SOMENTE NO PLANO COMPLETO",
    freeLabel: "GRÁTIS",
  },
  bonuses: [
    {
      front: "/images/bonus-1-frente.webp",
      back: "/images/bonus-1-verso.webp",
      title: "Tutorial de Montagem",
      titleBreak: "Tutorial de\nMontagem",
      desc: "Orientações passo a passo para montagem, impressão, recorte e finalização das lembrancinhas.",
      price: "R$ 19,90",
    },
    {
      front: "/images/bonus-2-frente.webp",
      back: "/images/bonus-2-verso.webp",
      title: "Lembrancinhas Dinâmicas",
      titleBreak: "Lembrancinhas\nDinâmicas",
      desc: "Modelos interativos para usar em atividades, reflexões e momentos especiais dos encontros.",
      price: "R$ 29,90",
    },
    {
      front: "/images/bonus-3-frente.webp",
      back: "/images/bonus-3-verso.webp",
      title: "Calendário Catequético",
      titleBreak: "Calendário\nCatequético",
      desc: "Organizador de encontros, datas e momentos importantes da crisma com clareza e praticidade.",
      price: "R$ 19,90",
    },
    {
      front: "/images/bonus-4-frente.webp",
      back: "/images/bonus-4-verso.webp",
      title: "Santos Católicos",
      titleBreak: "Santos\nCatólicos",
      desc: "Modelos com santos para inspirar fé e servir como exemplo de vida cristã aos crismandos.",
      price: "R$ 29,90",
    },
    {
      front: "/images/bonus-5-frente.webp",
      back: "/images/bonus-5-verso.webp",
      title: "Marcador de Páginas",
      titleBreak: "Marcador de\nPáginas",
      desc: "+100 marcadores católicos para entregar com a Bíblia, caderno ou material da catequese.",
      price: "R$ 9,90",
    },
    {
      front: "/images/bonus-6-frente.webp",
      back: "/images/bonus-6-verso.webp",
      title: "Tags Católica",
      titleBreak: "Tags\nCatólica",
      desc: "Tags de fé para complementar lembrancinhas, embalagens e mimos dos encontros.",
      price: "R$ 12,90",
    },
  ],
  pricing: {
    titleLead: "APROVEITE ENQUANTO",
    titleHighlight: "O PLANO COMPLETO ESTÁ EM PROMOÇÃO!",
    plans: [
      {
        id: "basic",
        label: "PARA COMEÇAR HOJE",
        title: "Plano Básico",
        image: "/images/plano-completo.webp",
        imageAlt: "Plano Básico",
        featured: false,
        oldPrice: "de R$ 39,90",
        price: "R$ 17,90",
        installments: "ou 4x de R$ 4,47 no cartão",
        items: [
          "50 Modelos de lembrancinhas para Crisma",
          "Material em PDF para imprimir e usar",
          "Acesso imediato após a compra",
        ],
        mutedItems: [
          "Não inclui os bônus do Plano Completo",
        ],
        ctaText: "QUERO AS LEMBRANCINHAS",
        ctaHref: "https://pay.hotmart.com/Q106149258M",
      },
      {
        id: "premium",
        title: "Plano Completo",
        image: "/images/plano-completo.webp",
        imageAlt: "Plano Completo",
        featured: true,
        badgeText: "MAIS VENDIDO",
        extraNote: "✅ TODOS OS BÔNUS INCLUSOS",
        oldPrice: "de R$ 162,30",
        price: "R$ 27,90",
        installments: "ou 4x de R$ 6,97 no cartão",
        items: [
          "50 Modelos de lembrancinhas para Crisma",
          "Mensagens, versículos e símbolos católicos",
          "Lembrancinhas com espaços para doces e brindes",
          "Material em PDF para baixar, imprimir e usar",
          "6 bônus exclusivos (Tutorial, Dinâmicas, Calendário, Santos, Marcadores, Tags)",
          "Envio imediato por e-mail",
          "Acesso vitalício ao material",
        ],
        ctaText: "QUERO AS LEMBRANCINHAS",
        ctaHref: "https://pay.hotmart.com/Q106200323I",
      },
    ],
  },
  guarantee: {
    marqueeText: "GARANTIA 30 DIAS • RISCO ZERO • SATISFAÇÃO OU DINHEIRO DE VOLTA • ",
    marqueeGradient: "linear-gradient(135deg, #A8C5DE 0%, #2A4A6B 55%, #1E3A52 100%)",
    icon: "/images/garantia-30-dias.webp",
    iconAlt: "Garantia de 30 dias",
    title: "Compra 100% segura e garantida!",
    body: "Você tem **30 dias de garantia** para testar o material. Se não gostar por qualquer motivo, devolvemos 100% do valor. Sem perguntas, sem burocracia.",
  },
  access: {
    title: "Como você vai receber suas lembrancinhas",
    steps: [
      { num: "01", title: "Conclua sua compra", desc: "Após o pagamento, seu acesso é liberado automaticamente." },
      { num: "02", title: "Receba no e-mail", desc: "As instruções chegam diretamente no e-mail cadastrado na compra." },
      { num: "03", title: "Baixe os PDFs", desc: "Tudo organizado em PDF, pronto para baixar e usar." },
      { num: "04", title: "Imprima e entregue", desc: "Modelos preparados para impressão, é só imprimir e entregar." },
    ],
  },
  faq: {
    title: "Perguntas Frequentes",
    items: [
      { q: "Como vou receber as lembrancinhas?", a: "Você recebe os arquivos por e-mail logo após a confirmação da compra." },
      { q: "As lembrancinhas são físicas ou digitais?", a: "São digitais. Você recebe os arquivos em PDF para baixar, imprimir e entregar nos encontros." },
      { q: "Preciso editar alguma coisa?", a: "Não. As lembrancinhas já vêm prontas. Você não precisa de Canva, programas ou design." },
      { q: "Posso imprimir em casa?", a: "Sim. Os arquivos são em formato A4, prontos para imprimir em casa, na paróquia ou gráfica rápida." },
      { q: "O material serve para quem tem pouca experiência com tecnologia?", a: "Sim. É só abrir o PDF, imprimir, recortar e entregar. Não exige habilidade técnica." },
      { q: "O que vem no Plano Completo?", a: "O produto principal (50 lembrancinhas) + 6 bônus: Tutorial de Montagem, Lembrancinhas Dinâmicas, Calendário Catequético, Santos Católicos, Marcador de Páginas e Tags Católica." },
      { q: "E se eu comprar e não gostar?", a: "Você tem 30 dias de garantia. Se não for para você, basta solicitar o reembolso e devolvemos 100% do valor." },
      { q: "Para quem esse material é indicado?", a: "Para catequistas, coordenadoras e voluntárias da paróquia que querem encontros mais bonitos sem perder tempo criando do zero." },
    ],
  },
  footer: {
    updateTitle: "Material em constante atualização",
    updateBody: "As Lembrancinhas para Crisma recebem novos modelos periodicamente. Ao adquirir agora, você garante acesso vitalício e todas as atualizações futuras.",
    copyright: "Copyright © 2026 | Todos os direitos reservados. Este material é protegido pela Lei nº 9.610/98, sendo proibida a reprodução total ou parcial sem autorização.",
    missionText: "Prepare encontros de Crisma mais bonitos e significativos com lembrancinhas de Fé e Propósito",
    privacyUrl: "#",
    termsUrl: "#",
    privacyLabel: "Política de Privacidade",
    termsLabel: "Termos de Uso",
  },
}
