import type { OfferConfig } from '@/types/offer'

export const OFFER: OfferConfig = {
  meta: {
    title: "50 Modelos de Lembrancinhas para Crisma",
    description: "50 modelos de lembrancinhas para Crisma prontas para imprimir, organizadas por temas com mensagens de fé, versículos e símbolos católicos.",
  },
  palette: {
    brand: "#4A0E1A",
    brandDeep: "#3A0A14",
    brandInk: "#2A0610",
    brandDark: "#5D1522",
    brandLight: "#C4818F",
    brandSubtle: "#F5E8EB",
    cta: "#16A34A",
    ctaDeep: "#11863D",
    ctaDarkest: "#0E6B31",
    accent: "#C8860A",
    yellow: "#F5C518",
    bg: "#FEF5EC",
    bgAlt: "#F5C518",
  },
  hero: {
    pill: "LEMBRANCINHAS CRISTÃ",
    titleLine1: "+50 Modelos Exclusivos",
    titleLine2: "de Lembrancinhas para Crisma",
    titleLine3: "Organizadas por temas, prontas para imprimir e entregar.",
    image: "/images/lembrancinhas/Plano Completo.webp",
    imageAlt: "Lembrancinhas para Crisma",
    imageWidth: 340,
    imageHeight: 425,
    subtitle: "Tenha em mãos +50 Modelos de Lembrancinhas, fáceis de montar e organizados por temas para entregar ao crismando sem precisar criar nada do zero.",
    ctaText: "QUERO AS LEMBRANCINHAS",
    timerLabel: "BÔNUS ENCERRAM EM",
    marqueeText: "+50 Modelos de Lembrancinhas • PDF A4 – Alta Qualidade • Acesso Imediato • ",
    marqueeGradient: "linear-gradient(90deg, #8B5E0A 0%, #C8860A 30%, #E8A020 55%, #F5C518 80%, #C8860A 100%)",
    bullets: [],
  },
  socialProof: {
    title: "Catequistas de todo o Brasil já usam e aprovam",
    testimonials: [
      { src: "/images/lembrancinhas/Depoimento (1).webp", alt: "Depoimento 1", gradient: "linear-gradient(90deg, #0A1F44, #081733)" },
      { src: "/images/lembrancinhas/Depoimento (2).webp", alt: "Depoimento 2", gradient: "linear-gradient(90deg, #16A34A, #11863D)" },
      { src: "/images/lembrancinhas/Depoimento (3).webp", alt: "Depoimento 3", gradient: "linear-gradient(90deg, #B0B8C7, #0A1F44)" },
      { src: "/images/lembrancinhas/Depoimento (4).webp", alt: "Depoimento 4", gradient: "linear-gradient(90deg, #081733, #061226)" },
      { src: "/images/lembrancinhas/Depoimento (5).webp", alt: "Depoimento 5", gradient: "linear-gradient(90deg, #16A34A, #E11D2E)" },
      { src: "/images/lembrancinhas/Depoimento (6).webp", alt: "Depoimento 6", gradient: "linear-gradient(90deg, #0A1F44, #16A34A)" },
      { src: "/images/lembrancinhas/Depoimento (7).webp", alt: "Depoimento 7", gradient: "linear-gradient(90deg, #B0B8C7, #081733)" },
      { src: "/images/lembrancinhas/Depoimento (8).webp", alt: "Depoimento 8", gradient: "linear-gradient(90deg, #E11D2E, #0A1F44)" },
    ],
  },
  counter: {
    prefix: "+ de",
    target: 50,
    label: "Modelos de Lembrancinhas para Crisma",
  },
  kitCards: {
    heading1: "Veja como são os modelos que você vai receber:",
    images: [
      { src: "/images/lembrancinhas/Imagem (1).webp", alt: "Lembrancinha para Crisma 1", width: 208, height: 192 },
      { src: "/images/lembrancinhas/Imagem (2).webp", alt: "Lembrancinha para Crisma 2", width: 208, height: 192 },
      { src: "/images/lembrancinhas/Imagem (3).webp", alt: "Lembrancinha para Crisma 3", width: 208, height: 192 },
      { src: "/images/lembrancinhas/Imagem (4).webp", alt: "Lembrancinha para Crisma 4", width: 208, height: 192 },
      { src: "/images/lembrancinhas/Imagem (5).webp", alt: "Lembrancinha para Crisma 5", width: 208, height: 192 },
      { src: "/images/lembrancinhas/Imagem (6).webp", alt: "Lembrancinha para Crisma 6", width: 208, height: 192 },
      { src: "/images/lembrancinhas/Imagem (7).webp", alt: "Lembrancinha para Crisma 7", width: 188, height: 80 },
      { src: "/images/lembrancinhas/Imagem (8).webp", alt: "Lembrancinha para Crisma 8", width: 188, height: 80 },
      { src: "/images/lembrancinhas/Imagem (9).webp", alt: "Lembrancinha para Crisma 9", width: 188, height: 80 },
      { src: "/images/lembrancinhas/Imagem (10).webp", alt: "Lembrancinha para Crisma 10", width: 188, height: 80 },
    ],
  },
  benefits: {
    title: "Por que centenas de catequistas estão comprando as Lembrancinhas?",
    ctaText: "QUERO AS LEMBRANCINHAS",
    items: [
      { icon: "⏱️", title: "Praticidade", desc: "50 modelos prontos, você baixa, imprime e entrega em menos de 10 minutos." },
      { icon: "📋", title: "Variedade", desc: "Cada tema já tem sua lembrancinha: Cura, Espírito Santo, Fé, Apóstolos, Gratidão e mais." },
      { icon: "💝", title: "Impacto", desc: "Uma lembrancinha bonita transforma um encontro comum em um momento que o crismando guarda." },
      { icon: "🙏", title: "Propósito", desc: "Você não entrega só papel, entrega uma mensagem de fé que marca o coração de um jovem." },
    ],
  },
  urgency: {
    pill: "OPORTUNIDADE ÚNICA",
    title: "Deixe cada encontro mais especial com uma lembrancinha de fé pronta para entregar",
    highlight: "",
    body: "Enquanto você pensa, outras catequistas já estão baixando os modelos. O preço promocional não dura para sempre.",
    ctaText: "QUERO AS LEMBRANCINHAS",
    trust: ["ACESSO IMEDIATO • ACESSO VITALÍCIO"],
  },
  idealPara: {
    pill: "É PARA VOCÊ",
    title: "Ideal para você que deseja",
    subtitle: "Feito para catequistas e coordenadoras que querem encontros mais bonitos sem perder tempo.",
    items: [
      { icon: "📋", title: "Praticidade", desc: "Ter uma lembrancinha pronta sem precisar criar nada do zero" },
      { icon: "💡", title: "Variedade", desc: "Ter modelos para cada tema da Crisma sem repetir" },
      { icon: "💝", title: "Recordação", desc: "Entregar algo que o crismando leva para casa e guarda" },
      { icon: "🙏", title: "Fé e Propósito", desc: "Transmitir mensagens que fazem sentido na caminhada de fé" },
    ],
  },
  deliverables: {
    pill: "CONTEÚDO DO KIT",
    title: "Tudo o que você vai receber",
    titleHighlight: "",
    image: "/images/lembrancinhas/Plano Completo.webp",
    imageAlt: "Lembrancinhas para Crisma",
    bullets: [
      "+50 Modelos de Lembrancinhas para Crisma",
      "Lembrancinhas de Cura",
      "Lembrancinhas do Espírito Santo",
      "Lembrancinhas de Fé",
      "Lembrancinhas dos Apóstolos",
      "Lembrancinhas de Gratidão",
      "Lembrancinhas de Propósito",
      "Lembrancinhas Descontraídas e muito mais",
      "Arquivos em PDF prontos para impressão (A4)",
    ],
  },
  bonusSection: {
    pill: "EXTRA INCLUÍDO",
    titleLead: "5 BÔNUS",
    titleHighlight: "EXCLUSIVOS",
    subtitle: "Além dos 50 Modelos, ao adquirir o Plano Completo você também recebe 06 bônus especiais.",
    cardLabel: "BÔNUS",
    touchHint: "Toque na imagem acima para ver o conteúdo.",
    backHint: "Toque para voltar",
    timerText: "BÔNUS DISPONÍVEIS SOMENTE\nNO PLANO COMPLETO",
    freeLabel: "GRÁTIS",
  },
  bonuses: [
    {
      front: "/images/lembrancinhas/bonus-1-frente.webp",
      back: "/images/lembrancinhas/bonus-1-verso.webp",
      title: "Montagem das Lembrancinhas",
      titleBreak: "Montagem das\nLembrancinhas",
      desc: "Orientações passo a passo para montagem, impressão, recorte e finalização de cada lembrancinha.",
      price: "R$ 19,90",
    },
    {
      front: "/images/lembrancinhas/bonus-2-frente.webp",
      back: "/images/lembrancinhas/bonus-2-verso.webp",
      title: "Lembrancinhas Dinâmicas",
      titleBreak: "Lembrancinhas\nDinâmicas",
      desc: "Modelos focados na interação, para usar em atividades, reflexões e momentos especiais dos encontros.",
      price: "R$ 29,90",
    },
    {
      front: "/images/lembrancinhas/bonus-3-frente.webp",
      back: "/images/lembrancinhas/bonus-3-verso.webp",
      title: "Calendário Catequético",
      titleBreak: "Calendário\nCatequético",
      desc: "Organizador de encontros, datas e momentos importantes da crisma com clareza e praticidade.",
      price: "R$ 19,90",
    },
    {
      front: "/images/lembrancinhas/bonus-4-frente.webp",
      back: "/images/lembrancinhas/bonus-4-verso.webp",
      title: "Santos Católicos",
      titleBreak: "Santos\nCatólicos",
      desc: "Modelos com santos para inspirar fé e servir como exemplo de vida cristã aos crismandos.",
      price: "R$ 29,90",
    },
    {
      front: "/images/lembrancinhas/bonus-5-frente.webp",
      back: "/images/lembrancinhas/bonus-5-verso.webp",
      title: "150 Marcadores Católicos",
      titleBreak: "150 Marcadores\nCatólicos",
      desc: "+150 marcadores católicos para entregar com a Bíblia, caderno ou material da catequese.",
      price: "R$ 9,90",
    },
  ],
  pricing: {
    titleLead: "APROVEITE ENQUANTO",
    titleHighlight: "O PLANO COMPLETO ESTÁ EM PROMOÇÃO!",
    plans: [
      {
        id: "basic",
        title: "Plano Básico",
        image: "/images/lembrancinhas/Plano Básico.webp",
        imageAlt: "Plano Básico",
        featured: false,
        oldPrice: "de R$ 39,90",
        price: "R$ 17,90",
        installments: "ou 4x de R$ 4,47 no cartão",
        items: [
          "50 Modelos de Lembrancinhas para Crisma",
          "Lembrancinhas organizadas por temas (Sem Bônus)",
          "Arquivos em PDF prontos para impressão (A4)",
          "Material prático e organizado",
        ],
        mutedItems: [
          "Não inclui os bônus do Plano Completo",
        ],
        ctaText: "QUERO AS LEMBRANCINHAS",
        ctaHref: "https://ggcheckout.app/checkout/v5/dHk0JD3TBWiyj6MKWQP0",
      },
      {
        id: "premium",
        title: "Plano Completo",
        image: "/images/lembrancinhas/Plano Completo.webp",
        imageAlt: "Plano Completo",
        featured: true,
        oldPrice: "de R$ 162,30",
        price: "R$ 27,90",
        installments: "ou 4x de R$ 6,97 no cartão",
        items: [
          "50 Modelos de Lembrancinhas para Crisma",
          "Temas: Cura, Espírito Santo, Fé, Apóstolos, Gratidão, Propósito, Descontraídas, Oração, Motivação e Delicadas",
          "🎁 Bônus 01: Montagem de cada Lembrancinha",
          "🎁 Bônus 02: Lembrancinhas Dinâmicas",
          "🎁 Bônus 03: Calendário Catequético",
          "🎁 Bônus 04: Lembrancinhas de Santos Católicos",
          "🎁 Bônus 05: 150 Marcadores Católicos",
          "Lembrancinhas organizadas por temas",
          "Arquivos em PDF prontos para impressão (A4)",
          "Material prático e organizado",
          "Envio imediato por e-mail",
          "Acesso vitalício ao material",
        ],
        ctaText: "QUERO AS LEMBRANCINHAS",
        ctaHref: "https://ggcheckout.app/checkout/v5/M5N8grnzZN1q1S3WHGEU",
      },
    ],
  },
  guarantee: {
    marqueeText: "GARANTIA 30 DIAS • RISCO ZERO • SATISFAÇÃO OU DINHEIRO DE VOLTA • ",
    marqueeGradient: "linear-gradient(90deg, #8B5E0A 0%, #C8860A 30%, #E8A020 55%, #F5C518 80%, #C8860A 100%)",
    icon: "/images/lembrancinhas/garantia-30-dias.webp",
    iconAlt: "Garantia de 30 dias",
    title: "Compra 100% segura e garantida!",
    body: "Você tem **30 dias de garantia** para testar o material. Se não gostar por qualquer motivo, devolvemos 100% do valor. Sem perguntas, sem burocracia.",
  },
  access: {
    title: "Como você vai receber suas lembrancinhas",
    steps: [
      { num: "01", title: "Conclua sua compra", desc: "Após o pagamento, seu acesso é liberado automaticamente." },
      { num: "02", title: "Receba no e-mail", desc: "As instruções chegam diretamente no e-mail cadastrado na compra." },
      { num: "03", title: "Baixe os PDFs", desc: "Tudo organizado em PDF, pronto para baixar e usar." },
      { num: "04", title: "Imprima e entregue", desc: "Modelos preparados para impressão, é só imprimir e entregar." },
    ],
  },
  faq: {
    title: "Perguntas Frequentes",
    items: [
      { q: "Como vou receber as lembrancinhas?", a: "Você recebe os arquivos por e-mail logo após a confirmação da compra." },
      { q: "As lembrancinhas são físicas ou digitais?", a: "São digitais. Você recebe os arquivos em PDF para baixar, imprimir e entregar nos encontros." },
      { q: "Preciso editar alguma coisa?", a: "Não. As lembrancinhas já vêm prontas. Você não precisa de Canva, programas ou design." },
      { q: "O que vem no Plano Completo?", a: "O produto principal (50 lembrancinhas) + 5 bônus: Montagem, Lembrancinhas Dinâmicas, Calendário Catequético, Santos Católicos e 150 Marcadores Católicos." },
      { q: "E se eu comprar e não gostar?", a: "Você tem 30 dias de garantia. Se não for para você, basta solicitar o reembolso e devolvemos 100% do valor." },
    ],
  },
  footer: {
    updateTitle: "Material em constante atualização",
    updateBody: "As Lembrancinhas para Crisma recebem novos modelos periodicamente. Ao adquirir agora, você garante acesso vitalício e todas as atualizações futuras.",
    copyright: "Copyright © 2026 | Todos os direitos reservados. Este material é protegido pela Lei nº 9.610/98, sendo proibida a reprodução total ou parcial sem autorização.",
    missionText: "Prepare encontros de Crisma mais bonitos e significativos com lembrancinhas de Fé e Propósito",
    privacyUrl: "/lembrancinhas/politica-de-privacidade",
    termsUrl: "/lembrancinhas/termos-de-uso",
    privacyLabel: "Política de Privacidade",
    termsLabel: "Termos de Uso",
  },
}
